import { commonColors } from './common'

export const semanticColors = {
  light: {
    primary: {
      solid: {
        DEFAULT: commonColors.primary['600'],
        fg: commonColors.white,
        hover: commonColors.primary['700'],
        active: commonColors.primary['800'],
        disable: commonColors.neutral['100'],
        'disable-fg': commonColors.neutral['400'],
      },
      outline: {
        fg: commonColors.primary['700'],
        border: commonColors.primary['300'],
        hover: commonColors.primary['50'],
        active: commonColors.primary['100'],
        'disable-fg': commonColors.neutral['400'],
        'disable-border': commonColors.neutral['200'],
      },
      plain: {
        fg: commonColors.primary['700'],
        hover: commonColors.primary['50'],
        active: commonColors.primary['100'],
        'disable-fg': commonColors.neutral['400'],
      },
      soft: {
        DEFAULT: commonColors.primary['50'],
        fg: commonColors.primary['700'],
        hover: commonColors.primary['100'],
        active: commonColors.primary['200'],
        'active-fg': commonColors.primary['800'],
        disable: commonColors.neutral['50'],
        'disable-fg': commonColors.neutral['400'],
      },
    },
    secondary: {
      solid: {
        DEFAULT: commonColors.secondary['600'],
        fg: commonColors.white,
        hover: commonColors.secondary['700'],
        active: commonColors.secondary['800'],
        disable: commonColors.neutral['100'],
        'disable-fg': commonColors.neutral['400'],
      },
      outline: {
        fg: commonColors.secondary['700'],
        border: commonColors.secondary['300'],
        hover: commonColors.secondary['50'],
        active: commonColors.secondary['100'],
        'disable-fg': commonColors.neutral['400'],
        'disable-border': commonColors.neutral['200'],
      },
      plain: {
        fg: commonColors.secondary['700'],
        hover: commonColors.secondary['50'],
        active: commonColors.secondary['100'],
        'disable-fg': commonColors.neutral['400'],
      },
      soft: {
        DEFAULT: commonColors.secondary['50'],
        fg: commonColors.secondary['700'],
        hover: commonColors.secondary['100'],
        active: commonColors.secondary['200'],
        'active-fg': commonColors.secondary['800'],
        disable: commonColors.neutral['50'],
        'disable-fg': commonColors.neutral['400'],
      },
    },
    white: {
      solid: {
        DEFAULT: commonColors.primary['600'],
        fg: commonColors.white,
        hover: commonColors.primary['700'],
        active: commonColors.primary['800'],
        disable: commonColors.neutral['100'],
        'disable-fg': commonColors.neutral['400'],
      },
      outline: {
        fg: commonColors.primary['700'],
        border: commonColors.primary['300'],
        hover: commonColors.primary['50'],
        active: commonColors.primary['100'],
        'disable-fg': commonColors.neutral['400'],
        'disable-border': commonColors.neutral['200'],
      },
      plain: {
        fg: commonColors.primary['700'],
        hover: commonColors.primary['50'],
        active: commonColors.primary['100'],
        'disable-fg': commonColors.neutral['400'],
      },
      soft: {
        DEFAULT: commonColors.primary['50'],
        fg: commonColors.primary['700'],
        hover: commonColors.primary['100'],
        active: commonColors.primary['200'],
        'active-fg': commonColors.primary['800'],
        disable: commonColors.neutral['50'],
        'disable-fg': commonColors.neutral['400'],
      },
    },
    success: {
      solid: {
        DEFAULT: commonColors.success['600'],
        fg: commonColors.white,
        hover: commonColors.success['700'],
        active: commonColors.success['800'],
        disable: commonColors.neutral['100'],
        'disable-fg': commonColors.neutral['400'],
      },
      outline: {
        fg: commonColors.success['700'],
        border: commonColors.success['300'],
        hover: commonColors.success['50'],
        active: commonColors.success['100'],
        'disable-fg': commonColors.neutral['400'],
        'disable-border': commonColors.neutral['200'],
      },
      plain: {
        fg: commonColors.success['700'],
        hover: commonColors.success['50'],
        active: commonColors.success['100'],
        'disable-fg': commonColors.neutral['400'],
      },
      soft: {
        DEFAULT: commonColors.success['50'],
        fg: commonColors.success['700'],
        hover: commonColors.success['100'],
        active: commonColors.success['200'],
        'active-fg': commonColors.success['800'],
        disable: commonColors.neutral['50'],
        'disable-fg': commonColors.neutral['400'],
      },
    },
    warning: {
      solid: {
        DEFAULT: commonColors.warning['600'],
        fg: commonColors.white,
        hover: commonColors.warning['700'],
        active: commonColors.warning['800'],
        disable: commonColors.neutral['100'],
        'disable-fg': commonColors.neutral['400'],
      },
      outline: {
        fg: commonColors.warning['700'],
        border: commonColors.warning['300'],
        hover: commonColors.warning['50'],
        active: commonColors.warning['100'],
        'disable-fg': commonColors.neutral['400'],
        'disable-border': commonColors.neutral['200'],
      },
      plain: {
        fg: commonColors.warning['700'],
        hover: commonColors.warning['50'],
        active: commonColors.warning['100'],
        'disable-fg': commonColors.neutral['400'],
      },
      soft: {
        DEFAULT: commonColors.warning['50'],
        fg: commonColors.warning['700'],
        hover: commonColors.warning['100'],
        active: commonColors.warning['200'],
        'active-fg': commonColors.warning['800'],
        disable: commonColors.neutral['50'],
        'disable-fg': commonColors.neutral['400'],
      },
    },
    danger: {
      solid: {
        DEFAULT: commonColors.danger['600'],
        fg: commonColors.white,
        hover: commonColors.danger['700'],
        active: commonColors.danger['800'],
        disable: commonColors.neutral['100'],
        'disable-fg': commonColors.neutral['400'],
      },
      outline: {
        fg: commonColors.danger['700'],
        border: commonColors.danger['300'],
        hover: commonColors.danger['50'],
        active: commonColors.danger['100'],
        'disable-fg': commonColors.neutral['400'],
        'disable-border': commonColors.neutral['200'],
      },
      plain: {
        fg: commonColors.danger['700'],
        hover: commonColors.danger['50'],
        active: commonColors.danger['100'],
        'disable-fg': commonColors.neutral['400'],
      },
      soft: {
        DEFAULT: commonColors.danger['50'],
        fg: commonColors.danger['700'],
        hover: commonColors.danger['100'],
        active: commonColors.danger['200'],
        'active-fg': commonColors.danger['800'],
        disable: commonColors.neutral['50'],
        'disable-fg': commonColors.neutral['400'],
      },
    },
    neutral: {
      solid: {
        DEFAULT: commonColors.neutral['600'],
        fg: commonColors.white,
        hover: commonColors.neutral['700'],
        active: commonColors.neutral['800'],
        disable: commonColors.neutral['100'],
        'disable-fg': commonColors.neutral['400'],
      },
      outline: {
        fg: commonColors.neutral['700'],
        border: commonColors.neutral['300'],
        hover: commonColors.neutral['50'],
        active: commonColors.neutral['100'],
        'disable-fg': commonColors.neutral['400'],
        'disable-border': commonColors.neutral['200'],
      },
      plain: {
        fg: commonColors.neutral['700'],
        hover: commonColors.neutral['50'],
        active: commonColors.neutral['100'],
        'disable-fg': commonColors.neutral['400'],
      },
      soft: {
        DEFAULT: commonColors.neutral['50'],
        fg: commonColors.neutral['700'],
        hover: commonColors.neutral['100'],
        active: commonColors.neutral['200'],
        'active-fg': commonColors.neutral['800'],
        disable: commonColors.neutral['50'],
        'disable-fg': commonColors.neutral['400'],
      },
    },
    text: {
      primary: commonColors.neutral['800'],
      secondary: commonColors.neutral['700'],
      tertiary: commonColors.neutral['500'],
      disabled: commonColors.neutral['400'],
      icon: commonColors.neutral['800'], // removeable
      'icon-primary': commonColors.neutral['800'],
      'icon-secondary': commonColors.neutral['500'],
      contrast: commonColors.white,
    },
    background: {
      body: commonColors.white,
      level1: commonColors.neutral['50'],
      level2: commonColors.neutral['100'],
      level3: commonColors.neutral['200'],
      surface: commonColors.white, // card, sheet, drawer
      popup: commonColors.white, // dropdown, menu
      tooltip: commonColors.neutral[500], // slider tooltip
      backdrop: 'rgba(23, 24, 29, .4)', // 40%
      hover: commonColors.neutral['100'],
    },
    divider: 'rgba(35,36,38, 0.08)',
    focus: commonColors.primary['100'],
  },
  dark: {
    primary: {
      solid: {
        DEFAULT: commonColors.primary['600'],
        fg: commonColors.white,
        hover: commonColors.primary['700'],
        active: commonColors.primary['800'],
        disable: commonColors.neutral['800'],
        'disable-fg': commonColors.neutral['600'],
      },
      outline: {
        fg: commonColors.primary['300'],
        border: commonColors.primary['700'],
        hover: commonColors.primary['900'],
        active: commonColors.primary['800'],
        'disable-fg': commonColors.neutral['600'],
        'disable-border': commonColors.neutral['800'],
      },
      plain: {
        fg: commonColors.primary['300'],
        hover: commonColors.primary['900'],
        active: commonColors.primary['800'],
        'disable-fg': commonColors.neutral['600'],
      },
      soft: {
        DEFAULT: commonColors.primary['900'],
        fg: commonColors.primary['300'],
        hover: commonColors.primary['800'],
        active: commonColors.primary['700'],
        'active-fg': commonColors.primary['100'],
        disable: commonColors.neutral['800'],
        'disable-fg': commonColors.neutral['600'],
      },
    },
    secondary: {
      solid: {
        DEFAULT: commonColors.secondary['600'],
        fg: commonColors.white,
        hover: commonColors.secondary['700'],
        active: commonColors.secondary['800'],
        disable: commonColors.neutral['800'],
        'disable-fg': commonColors.neutral['600'],
      },
      outline: {
        fg: commonColors.secondary['300'],
        border: commonColors.secondary['700'],
        hover: commonColors.secondary['900'],
        active: commonColors.secondary['800'],
        'disable-fg': commonColors.neutral['600'],
        'disable-border': commonColors.neutral['800'],
      },
      plain: {
        fg: commonColors.secondary['300'],
        hover: commonColors.secondary['900'],
        active: commonColors.secondary['800'],
        'disable-fg': commonColors.neutral['600'],
      },
      soft: {
        DEFAULT: commonColors.secondary['900'],
        fg: commonColors.secondary['300'],
        hover: commonColors.secondary['800'],
        active: commonColors.secondary['700'],
        'active-fg': commonColors.secondary['100'],
        disable: commonColors.neutral['800'],
        'disable-fg': commonColors.neutral['600'],
      },
    },
    success: {
      solid: {
        DEFAULT: commonColors.success['600'],
        fg: commonColors.white,
        hover: commonColors.success['700'],
        active: commonColors.success['800'],
        disable: commonColors.neutral['800'],
        'disable-fg': commonColors.neutral['600'],
      },
      outline: {
        fg: commonColors.success['300'],
        border: commonColors.success['700'],
        hover: commonColors.success['900'],
        active: commonColors.success['800'],
        'disable-fg': commonColors.neutral['600'],
        'disable-border': commonColors.neutral['800'],
      },
      plain: {
        fg: commonColors.success['300'],
        hover: commonColors.success['900'],
        active: commonColors.success['800'],
        'disable-fg': commonColors.neutral['600'],
      },
      soft: {
        DEFAULT: commonColors.success['900'],
        fg: commonColors.success['300'],
        hover: commonColors.success['800'],
        active: commonColors.success['700'],
        'active-fg': commonColors.success['100'],
        disable: commonColors.neutral['800'],
        'disable-fg': commonColors.neutral['600'],
      },
    },
    warning: {
      solid: {
        DEFAULT: commonColors.warning['600'],
        fg: commonColors.white,
        hover: commonColors.warning['700'],
        active: commonColors.warning['800'],
        disable: commonColors.neutral['800'],
        'disable-fg': commonColors.neutral['600'],
      },
      outline: {
        fg: commonColors.warning['300'],
        border: commonColors.warning['700'],
        hover: commonColors.warning['900'],
        active: commonColors.warning['800'],
        'disable-fg': commonColors.neutral['600'],
        'disable-border': commonColors.neutral['800'],
      },
      plain: {
        fg: commonColors.warning['300'],
        hover: commonColors.warning['900'],
        active: commonColors.warning['800'],
        'disable-fg': commonColors.neutral['600'],
      },
      soft: {
        DEFAULT: commonColors.warning['900'],
        fg: commonColors.warning['300'],
        hover: commonColors.warning['800'],
        active: commonColors.warning['700'],
        'active-fg': commonColors.warning['100'],
        disable: commonColors.neutral['800'],
        'disable-fg': commonColors.neutral['600'],
      },
    },
    danger: {
      solid: {
        DEFAULT: commonColors.danger['600'],
        fg: commonColors.white,
        hover: commonColors.danger['700'],
        active: commonColors.danger['800'],
        disable: commonColors.neutral['800'],
        'disable-fg': commonColors.neutral['600'],
      },
      outline: {
        fg: commonColors.danger['300'],
        border: commonColors.danger['700'],
        hover: commonColors.danger['900'],
        active: commonColors.danger['800'],
        'disable-fg': commonColors.neutral['600'],
        'disable-border': commonColors.neutral['800'],
      },
      plain: {
        fg: commonColors.danger['300'],
        hover: commonColors.danger['900'],
        active: commonColors.danger['800'],
        'disable-fg': commonColors.neutral['600'],
      },
      soft: {
        DEFAULT: commonColors.danger['900'],
        fg: commonColors.danger['300'],
        hover: commonColors.danger['800'],
        active: commonColors.danger['700'],
        'active-fg': commonColors.danger['100'],
        disable: commonColors.neutral['800'],
        'disable-fg': commonColors.neutral['600'],
      },
    },
    neutral: {
      solid: {
        DEFAULT: commonColors.neutral['600'],
        fg: commonColors.white,
        hover: commonColors.neutral['700'],
        active: commonColors.neutral['800'],
        disable: commonColors.neutral['800'],
        'disable-fg': commonColors.neutral['600'],
      },
      outline: {
        fg: commonColors.neutral['300'],
        border: commonColors.neutral['700'],
        hover: commonColors.neutral['900'],
        active: commonColors.neutral['800'],
        'disable-fg': commonColors.neutral['600'],
        'disable-border': commonColors.neutral['800'],
      },
      plain: {
        fg: commonColors.neutral['300'],
        hover: commonColors.neutral['900'],
        active: commonColors.neutral['800'],
        'disable-fg': commonColors.neutral['600'],
      },
      soft: {
        DEFAULT: commonColors.neutral['900'],
        fg: commonColors.neutral['300'],
        hover: commonColors.neutral['800'],
        active: commonColors.neutral['700'],
        'active-fg': commonColors.neutral['100'],
        disable: commonColors.neutral['800'],
        'disable-fg': commonColors.neutral['600'],
      },
    },
    text: {
      primary: commonColors.neutral['100'],
      secondary: commonColors.neutral['300'],
      tertiary: commonColors.neutral['500'],
      disabled: commonColors.neutral['600'],
      icon: commonColors.neutral['50'], // removeable
      'icon-primary': commonColors.neutral['50'],
      'icon-secondary': commonColors.neutral['400'],
      contrast: commonColors.white,
    },
    background: {
      body: commonColors.neutral['900'],
      level1: commonColors.neutral['900'],
      level2: commonColors.neutral['800'],
      level3: commonColors.neutral['700'],
      surface: commonColors.neutral['800'],
      popup: commonColors.neutral['800'], // dropdown, menu
      tooltip: commonColors.neutral['600'], // slider tooltip
      backdrop: 'rgba(0, 0, 0, .4)', // 40%
      hover: 'rgba(93, 98, 103, 0.3)', // migrate hover state
    },
    divider: 'rgba(93,98,103, .75)',
    focus: commonColors.primary['700'],
  },
}
