const TOAST_REMOVE_DELAY = 1000000
const TOAST_LIMIT = 10

const ACTION_TYPES = {
  ADD_TOAST: 'ADD_TOAST',
  UPDATE_TOAST: 'UPDATE_TOAST',
  DISMISS_TOAST: 'DISMISS_TOAST',
  REMOVE_TOAST: 'REMOVE_TOAST',
} as const

export { TOAST_REMOVE_DELAY, TOAST_LIMIT, ACTION_TYPES }
