#!/bin/sh

commit_msg=$(git log -1 --pretty=%B)

if echo "$commit_msg" | grep -qiE "\[(skip[-\s]?ci|ci[-\s]?skip|skip ci|ci skip)\]"; then
  echo "Skipping Vercel Build CI"
  exit 0
else
  echo "Continue to build on Vercel"
  exit 1
fi
