name: Discord release notify

inputs:
  github-token:
    description: 'Token to access the github'
    required: false
  discord-webhook:
    description: 'The Discord webhook URL'
    required: true
  # Data JSON format: [{ name: "package-1", version: 1.0.0, tag_name: "package-1@1.0.0", ignore_npm_released: false }, ...]
  tags-info:
    description: 'JSON array of name, version, tag_name and ignore_npm_released of released tags'
    required: true
  repo:
    description: 'The owner and repository name'
    required: true
  server-url:
    description: 'The URL of the GitHub server'
    required: true

runs:
  using: "composite"
  steps:
    - name: Get current time
      uses: josStorer/get-current-time@v2
      id: current-time
      with:
        format: MMMM Do YYYY, h:mm a
        utcOffset: '+07:00'

    - name: Send Discord Msg
      shell: bash
      env:
        TAGS_INFO: ${{ inputs.tags-info }}
        HOST: ${{ inputs.server-url }}
        REPO: ${{ inputs.repo }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        RELEASED_TIME: ${{ steps.current-time.outputs.formattedTime }}
        DISCORD_WEBHOOK: ${{ inputs.discord-webhook }}
        DISCORD_USERNAME: "Github Release"
        DISCORD_AVATAR: https://cdn.discordapp.com/avatars/1176117154010120202/df91181b3f1cf0ef1592fbe18e0962d7.webp?size=80
      run: pnpm release:notify
