name: Build and Deploy to GKE Prod

on:
  workflow_dispatch:
  push:
    branches:
      - cicd
  release:
    types: [released]
      
# Environment variables available to all jobs and steps in this workflow
env:
  REGISTRY_HOSTNAME: gcr.io
  GKE_PROJECT: console-labs-prod
  IMAGE: consolelabs/mochi-web
  K8S_ENVIRONMENT: prod
  SHA: ${{ github.sha }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - name: Setup Docker
        run: |
          gcloud auth configure-docker gcr.io

      # Overwrite GITHUB_SHA
      - name: Set SHA
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "SHA=${GITHUB_SHA}-$(date +%Y%m%d%H%M%S)" >> "$GITHUB_ENV"
      # Build & Push the Docker image
      - name: Build & Push
        run: |
          docker build -t $REGISTRY_HOSTNAME/$GKE_PROJECT/$IMAGE:${GITHUB_REF_NAME} .   
          docker push $REGISTRY_HOSTNAME/$GKE_PROJECT/$IMAGE:${GITHUB_REF_NAME}
          docker tag $REGISTRY_HOSTNAME/$GKE_PROJECT/$IMAGE:${GITHUB_REF_NAME} $REGISTRY_HOSTNAME/$GKE_PROJECT/$IMAGE:${SHA}
          docker push $REGISTRY_HOSTNAME/$GKE_PROJECT/$IMAGE:${SHA}

      # Setup kustomize
      # - name: Setup kustomize
      #   run: |
      #     curl -o kustomize --location https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
      #     chmod u+x ./kustomize
      #     mv kustomize /tmp
      # - name: Checkout consolelabs/infrastructure
      #   uses: actions/checkout@master
      #   with:
      #     repository: consolelabs/infrastructure
      #     token: ${{ secrets.GH_PAT }}
      #     path: ./infrastructure
      #     ref: main
      # - name: Update discord version
      #   run: |
      #     cd ./infrastructure/tono-discord/$K8S_ENVIRONMENT
      #     git config user.name jphuc96
      #     git config user.email jphuc96@gmail.com
      #     /tmp/kustomize edit set image $REGISTRY_HOSTNAME/$GKE_PROJECT/$IMAGE=$REGISTRY_HOSTNAME/$GKE_PROJECT/$IMAGE:${SHA}
      #     git commit -am "[skip ci] tono-discord ${K8S_ENVIRONMENT} image update"
      #     git push origin main
          