name: Release

on:
  push:
    paths:
      - ".changeset/**"
      - "packages/**"
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          # see `fetch-depth` in README: https://github.com/actions/checkout#checkout-v3,
          # we set to `0` so the referenced commits are available for the command below
          fetch-depth: 0

      - name: Prepare Environment
        uses: ./.github/actions/setup-env
        timeout-minutes: 10

      - name: Creating .npmrc file
        run: |
          echo "NPM_TOKEN=${{ secrets.NPM_TOKEN }}" >> $GITHUB_ENV
          cp .npmrc.example .npmrc
          sed -i "s/NPM_ACCESS_TOKEN/$NPM_TOKEN/g" .npmrc

      - name: Build
        run: pnpm build:packages

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          publish: pnpm release
          version: pnpm version-packages
          commit: 'release: bump package(s)'

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
