name: Release
permissions:
  id-token: write
  contents: write
  packages: write
  pull-requests: write
  issues: read

on:
  push:
    paths:
      - ".changeset/**"
      - "packages/**"
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      published: ${{ steps.changesets.outputs.published }}
      publishedPackages: ${{ toJson(steps.changesets.outputs.publishedPackages) }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          # see `fetch-depth` in README: https://github.com/actions/checkout#checkout-v4,
          # we set to `0` so the referenced commits are available for the command below
          fetch-depth: 0

      - name: Prepare Environment
        uses: ./.github/actions/setup-env
        timeout-minutes: 10

      - name: Creating .npmrc file
        run: |
          cp .npmrc.example .npmrc
          sed -i "s/NPM_ACCESS_TOKEN/$NPM_TOKEN/g" .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build
        run: pnpm build:packages

      - name: Create Release Pull Request or Publish Packages
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          version: pnpm version-packages
          commit: 'release: [skip apps] bump npm package(s)'
          title: 'release: [skip apps] npm package(s)'

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  notify:
    needs: [release]
    if: needs.release.outputs.published == 'true'
    name: Send Discord Notify
    uses: ./.github/workflows/discord-release-notify.yml
    secrets:
      discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
    with:
      tags-info: ${{ needs.release.outputs.publishedPackages }}
      repo: ${{ github.repository }}
      server-url: ${{ github.server_url }}
